name: Run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create Firebase service account JSON file
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "firebase.json"
          json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_INFO }}
      - name: Test with unittest
        run: python -m unittest -v
